### GET request to validate Token
GET http://localhost:4004/auth/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc2ODM4MDc1NSwiZXhwIjoxNzY4NDE2NzU1fQ.j-XdkSzAY7kfFbo9uvwwBg5VHZQujZMU3X62EHTx5qE